version: "3"

services:
  shepherd:
    image: <your local registry cache>/atsigncompany/shepherd:latest
    extra_hosts:
      - "<<your local registry cache>:<Local Network IP Address>
    environment:
      TZ: 'US/PST'
      SLEEP_TIME: '1h'
      VERBOSE: 'true'
      FILTER_SERVICES: 'label=com.docker.stack.image=<your local registry cache>/atsigncompany/secondary:prod'
      WITH_REGISTRY_AUTH: 'true'
      IMAGE_AUTOCLEAN_LIMIT: 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/root/.docker/config.json
    deploy:
      placement:
        constraints:
          - node.role == manager
