version: "3"

services:
  shepherd:
    image: atsigncompany/shepherd:latest
    environment:
      TZ: 'US/PST'
      SLEEP_TIME: '12h'
      VERBOSE: 'true'
      FILTER_SERVICES: 'label=com.docker.stack.image=atsigncompany/secondary:dev_env'
      WITH_REGISTRY_AUTH: 'true'
      IMAGE_AUTOCLEAN_LIMIT: 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/root/.docker/config.json
    deploy:
      placement:
        constraints:
          - node.role == manager
