#!/bin/bash
set -euo pipefail

server_version() {
  docker version -f "{{.Server.Version}}"
}

logger() {
  local log="$1"
  local is_verbose_log="${2:-false}"

  if [[ "$is_verbose_log" == "true" && "$verbose" == "true" || "$is_verbose_log" == "false" ]]; then
    echo "$(date) $log"
  fi
}

update_service() {
  local name="$1"
  local ignorelist="$2"
  local insecure_registry_flag="$3"
  local detach_option="$4"
  local registry_auth="$5"
  local no_resolve_image_flag="$6"
  local hostname="$7"
  local apprise_sidecar_url="$8"
  local image_autoclean_limit="$9"
  local image_with_digest image previousImage currentImage img_name image_ids image_ids_count
  if [[ " $ignorelist " != *" $name "* ]]; then
    image_with_digest="$(docker service inspect "$name" -f '{{.Spec.TaskTemplate.ContainerSpec.Image}}')"
    image=$(echo "$image_with_digest" | cut -d@ -f1)

    if ! DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect $insecure_registry_flag "$image" > /dev/null; then
      logger "Error updating service $name! Image $image does not exist or it is not available"
      return 3
    else
      logger "Trying to update service $name with image $image" "true"

      if ! docker service update "$name" $detach_option $registry_auth $no_resolve_image_flag --image="$image" > /dev/null; then
        logger "Service $name update failed on $hostname!"
        if [[ "${ROLLBACK_ON_FAILURE+x}" ]]; then
          logger "Rolling $name back"
          docker service update "$name" $detach_option $registry_auth $no_resolve_image_flag --rollback > /dev/null
        fi
        if [[ "$apprise_sidecar_url" != "" ]]; then
          title="[Shepherd] Service $name update failed on $hostname"
          body="$(date) Service $name failed to update to $(docker service inspect "$name" -f '{{.Spec.TaskTemplate.ContainerSpec.Image}}')"
          curl -X POST -H "Content-Type: application/json" --data "{\"title\": \"$title\", \"body\": \"$body\"}" "$apprise_sidecar_url"
        fi
        return 4    # continue with next service
      fi

      previousImage=$(docker service inspect "$name" -f '{{.PreviousSpec.TaskTemplate.ContainerSpec.Image}}')
      currentImage=$(docker service inspect "$name" -f '{{.Spec.TaskTemplate.ContainerSpec.Image}}')
      if [ "$previousImage" == "$currentImage" ]; then
        logger "No updates to service $name!" "true"
        return 1
      else
        logger "Service $name was updated!"
        if [[ "$apprise_sidecar_url" != "" ]]; then
          title="[Shepherd] Service $name updated on $hostname"
          body="$(date) Service $name was updated from $previousImage to $currentImage"
          curl -X POST -H "Content-Type: application/json" --data "{\"title\": \"$title\", \"body\": \"$body\"}" "$apprise_sidecar_url"
        fi

        if [[ "$image_autoclean_limit" != "" ]]; then
          logger "Cleaning up old docker images, leaving last $image_autoclean_limit"
          img_name=$(docker service inspect "$name" -f '{{.Spec.TaskTemplate.ContainerSpec.Image}}' | awk -F':' '{print $1}')
          image_ids=$(docker images -aq --filter=reference="$img_name")
          image_ids_count=$(echo "$image_ids" | wc -w)
          if [[ $image_ids_count > $image_autoclean_limit ]]; then
            docker container prune -f
            read -ra images_to_remove < <(echo "$image_ids" | xargs -n 1 | tail -n $(("$image_ids_count" - "$image_autoclean_limit")))
            docker rmi "${images_to_remove[@]}"
          fi
        fi
      fi
      return 0
    fi
    return 2
  fi
}

update_services() {
  local ignorelist="$1"
  local supports_detach_option=$2
  local supports_registry_auth=$3
  local supports_insecure_registry=$4
  local supports_no_resolve_image=$5
  local image_autoclean_limit=$6
  local registry_user="$7"
  local registry_password="$8"
  local registry_host="$9"
  local dont_wait="${10}"
  local sleep_time="${11}"
  local detach_option=""
  local registry_auth=""
  local insecure_registry_flag=""
  local no_resolve_image_flag=""
  local name
  local apprise_sidecar_url="${APPRISE_SIDECAR_URL:-}"
  local hostname
  hostname="${HOSTNAME:-$(hostname)}"

  [ "$supports_detach_option" = true ] && detach_option="--detach=false"
  [ "$dont_wait" = true ] && detach_option="--detach=true"
  [ "$supports_registry_auth" = true ] && registry_auth="--with-registry-auth"
  [ "$supports_insecure_registry" = true ] && insecure_registry_flag="--insecure"
  [ "$supports_no_resolve_image" = true ] && no_resolve_image_flag="--no-resolve-image"

  if [[ -n "$registry_user" ]]; then
    logger "Trying to login into registry $registry_host"
    echo "$registry_password" | docker login --username="$registry_user" --password-stdin "$registry_host"
  fi

  SERVICES=$(IFS=$'\n' docker service ls -q --format '{{.Name}}')
  
  # First do the services that aren't secondaries

  for name in $(echo "$SERVICES" | grep -v secondary); do
    update_service "$name" "$ignorelist" "$insecure_registry_flag" "$image" "$detach_option" "$registry_auth" "$no_resolve_image_flag" "$hostname" "$apprise_sidecar_url" "$image_autoclean_limit"
  done

  # Then do the services that are secondaries
  # start with the last secondary in the list
  for name in $(echo "$SERVICES" | grep secondary | tail -1); do
    update_service "$name" "$ignorelist" "$insecure_registry_flag" "$image" "$detach_option" "$registry_auth" "$no_resolve_image_flag" "$hostname" "$apprise_sidecar_url" "$image_autoclean_limit"
    # if the last secondary needs updating then update the rest
    if [ $? -eq 0 ]; then
      for name in $(echo "$SERVICES" | grep secondary ); do
        update_service "$name" "$ignorelist" "$insecure_registry_flag" "$image" "$detach_option" "$registry_auth" "$no_resolve_image_flag" "$hostname" "$apprise_sidecar_url" "$image_autoclean_limit"
      done
    fi
  done
}

# retrieve registry password from docker secrets or environment, in this order
get_registry_password() {
    local password_file_path="/run/secrets/shepherd_registry_password"
    if [[ -f "$password_file_path" ]]; then
        cat "$password_file_path"
    else
        echo "${REGISTRY_PASSWORD:-}"
    fi
}

main() {
  local sleep_time supports_detach_option supports_registry_auth verbose image_autoclean_limit ignorelist dont_wait
  local registry_user=""
  local registry_password=""
  local registry_host=""
  ignorelist="${IGNORELIST_SERVICES:-}"
  sleep_time="${SLEEP_TIME:-5m}"
  verbose="${VERBOSE:-true}"
  image_autoclean_limit="${IMAGE_AUTOCLEAN_LIMIT:-}"

  logger "Timezone set to $TZ"

  supports_detach_option=false
  if [[ $(expr "$(server_version)" ">=" "17.05") == "1" ]]; then
    supports_detach_option=true
    logger "Enabling synchronous service updates"
  fi

  supports_registry_auth=false
  if [[ ${REGISTRY_USER+x} ]]; then
    supports_registry_auth=true
    registry_user="${REGISTRY_USER}"
    registry_password="$(get_registry_password)"
    registry_host="${REGISTRY_HOST:-}"
    logger "Send given registry authentication details to swarm agents"
  fi

  if [[ ${WITH_REGISTRY_AUTH+x} ]]; then
    supports_registry_auth=true
    logger "Send registry authentication details to swarm agents"
  fi

  supports_insecure_registry=false
  if [[ ${WITH_INSECURE_REGISTRY+x} ]]; then
    supports_insecure_registry=true
    logger "Connection to insecure registry available"
  fi

  supports_no_resolve_image=false
  if [[ ${WITH_NO_RESOLVE_IMAGE+x} ]]; then
    supports_no_resolve_image=true
    logger "Deployment without resolving image"
  fi

  dont_wait=false
  if [[ ${DONT_WAIT+x} ]]; then
    dont_wait=true
    logger "Not waiting for services to converge"
  fi

  [[ "$ignorelist" != "" ]] && logger "Excluding services: $ignorelist"

  if [[ ${RUN_ONCE_AND_EXIT+x} ]]; then
    update_services "$ignorelist" "$supports_detach_option" "$supports_registry_auth" "$supports_insecure_registry" "$supports_no_resolve_image" "$image_autoclean_limit" "$registry_user" "$registry_password" "$registry_host" "$dont_wait" "$sleep_time"
  else
    while true; do
      update_services "$ignorelist" "$supports_detach_option" "$supports_registry_auth" "$supports_insecure_registry" "$supports_no_resolve_image" "$image_autoclean_limit" "$registry_user" "$registry_password" "$registry_host" "$dont_wait" "$sleep_time"
      logger "Sleeping $sleep_time before next run" "true"
      sleep "$sleep_time"
    done
  fi
}

main "$@"
